spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Origin
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
          routes:
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/ecommerce/user/**
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/ecommerce/product/**
            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/ecommerce/cart/**
            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/ecommerce/order/**
            - id: payment-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/ecommerce/payment/**
            - id: images
              uri: http://localhost:8081
              predicates:
                - Path=/images/**
            - id: inventory-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/ecommerce/inventory/**
            - id: catalog
              uri: http://localhost:8087
              predicates:
                - Path=/api/product/**

